name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  TEST_TAG: yorickp/maldet:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build docker
      uses: docker/build-push-action@v3
      with:
          context: .
          load: true      
          tags: ${{ env.TEST_TAG }}
    - name: Test
      run: docker run --rm ${{ env.TEST_TAG }}

# before_install:
#   - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL4000 --ignore DL3008 - < Dockerfile


